# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'none'


menu:
- {name: 'General Information', folder: 'topic', file: 'general-information.html'}
- {name: 'Topics', folder: 'topic', file: 'general-information.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
#social:
#- {icon: 'twitter', link: 'https://twitter.com/paululele'}
#- {icon: 'facebook', link: 'https://www.facebook.com/Le.Paul.94'}
#- {icon: 'instagram', link: 'https://instagram.com/paululele'}
#- {icon: 'envelope', link: 'mailto:l.nguyen.paul@gmail.com'}
#- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

post_date_prefix: 'Written on'
